name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  user-service-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./user-service/Dockerfile
          push: true
          tags: |
            lion3993vn/user-service:latest

  trip-service-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./trip-service/Dockerfile
          push: true
          tags: |
            lion3993vn/trip-service:latest

  bus-service-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./bus-service/Dockerfile
          push: true
          tags: |
            lion3993vn/bus-service:latest

  booking-service-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./booking-service/Dockerfile
          push: true
          tags: |
            lion3993vn/booking-service:latest

  deploy:
    runs-on: self-hosted
    needs:
      - user-service-build
      - trip-service-build
      - bus-service-build
      - booking-service-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Clean up old containers
        run: |
          docker-compose down || true
          docker system prune -af --volumes=false

      - name: Deploy with docker-compose
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        run: |
          docker-compose pull
          docker-compose up -d --remove-orphans

      - name: Wait for services to start
        run: sleep 30

      - name: Check container logs
        run: docker-compose logs

      - name: Verify running containers
        run: docker ps -a
